# Generated by Django 2.2.7 on 2019-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("subscriptions", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="last_checked",
            field=models.DateTimeField(null=True),
        )
    ]
