# Generated by Django 2.2.7 on 2019-11-04 13:03

import datetime
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
