# Generated by Django 2.2.7 on 2019-11-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_video_subscription_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='subscription_id',
            new_name='subscription',
        ),
    ]
