# Generated by Django 2.2.7 on 2019-11-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_auto_20191104_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(max_length=31),
        ),
    ]
