# Generated by Django 2.2.7 on 2019-11-05 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("subscriptions", "0012_video_url")]

    operations = [migrations.RemoveField(model_name="video", name="url")]
