# Generated by Django 2.2.7 on 2019-11-06 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0014_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='youtube_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'youtube_id')},
        ),
    ]
