# Generated by Django 2.2.7 on 2019-11-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20191106_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(),
        ),
    ]
