# Generated by Django 2.2.7 on 2019-11-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0015_auto_20191106_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='subscriptions.Subscription'),
        ),
    ]
