# Generated by Django 2.2.7 on 2019-11-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0017_auto_20191107_1903'),
        ('subscriptions', '0016_auto_20191108_1851'),
    ]

    operations = [
    ]
