# Generated by Django 2.2.13 on 2020-08-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0018_merge_20191108_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
