# Generated by Django 2.2.13 on 2020-08-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0020_remove_subscription_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.TimeField(null=True),
        ),
    ]
